//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApkShellext2.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NonLocalizeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NonLocalizeResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApkShellext2.Properties.NonLocalizeResources", typeof(NonLocalizeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 taskkill /f /im explorer.exe &amp; cd /d %USERPROFILE%\AppData\Local\Microsoft\Windows\Explorer &amp; attrib -h *.db &amp; del thumbcache_*.db iconcache_*.db &amp; cd /d %USERPROFILE%\AppData\Local &amp; del IconCache.db &amp; start explorer.exe 的本地化字符串。
        /// </summary>
        internal static string cmdClearCache {
            get {
                return ResourceManager.GetString("cmdClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap iconAmazonStore {
            get {
                object obj = ResourceManager.GetObject("iconAmazonStore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap iconAndroid {
            get {
                object obj = ResourceManager.GetObject("iconAndroid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap iconApkMirror {
            get {
                object obj = ResourceManager.GetObject("iconApkMirror", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap iconApple {
            get {
                object obj = ResourceManager.GetObject("iconApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap iconAppStore {
            get {
                object obj = ResourceManager.GetObject("iconAppStore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap iconGitHub {
            get {
                object obj = ResourceManager.GetObject("iconGitHub", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap iconGooglePlay {
            get {
                object obj = ResourceManager.GetObject("iconGooglePlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap iconMSStore {
            get {
                object obj = ResourceManager.GetObject("iconMSStore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap iconRename {
            get {
                object obj = ResourceManager.GetObject("iconRename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap iconUpdate {
            get {
                object obj = ResourceManager.GetObject("iconUpdate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap output {
            get {
                object obj = ResourceManager.GetObject("output", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Patreon {
            get {
                object obj = ResourceManager.GetObject("Patreon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap QR_Scan {
            get {
                object obj = ResourceManager.GetObject("QR_Scan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 %AppName%
        ///%Package%
        ///Version: %Version% %Revision% 的本地化字符串。
        /// </summary>
        internal static string strInfoTipDefault {
            get {
                return ResourceManager.GetString("strInfoTipDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %AppName%_%Version% 的本地化字符串。
        /// </summary>
        internal static string strRenamePatternDefault {
            get {
                return ResourceManager.GetString("strRenamePatternDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search in Stores 的本地化字符串。
        /// </summary>
        internal static string strSearchStore {
            get {
                return ResourceManager.GetString("strSearchStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.amazon.com/s?k={0}&amp;i=mobile-apps 的本地化字符串。
        /// </summary>
        internal static string urlAmazonAppStore {
            get {
                return ResourceManager.GetString("urlAmazonAppStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.apkmirror.com/?s={0}&amp;searchtype=apk 的本地化字符串。
        /// </summary>
        internal static string urlApkMirror {
            get {
                return ResourceManager.GetString("urlApkMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://itunes.apple.com/app/id{0} 的本地化字符串。
        /// </summary>
        internal static string urlAppleStore {
            get {
                return ResourceManager.GetString("urlAppleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://kkguo.github.io/apkshellext 的本地化字符串。
        /// </summary>
        internal static string urlGithubHome {
            get {
                return ResourceManager.GetString("urlGithubHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://kkguo.github.io/apkshellext/latest 的本地化字符串。
        /// </summary>
        internal static string urlGithubHomeLatest {
            get {
                return ResourceManager.GetString("urlGithubHomeLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://kkguo.github.io/apkshellext/index.html?version={0} 的本地化字符串。
        /// </summary>
        internal static string urlGithubHomeWithVersion {
            get {
                return ResourceManager.GetString("urlGithubHomeWithVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://play.google.com/store/search?q={0}&amp;c=apps 的本地化字符串。
        /// </summary>
        internal static string urlGooglePlay {
            get {
                return ResourceManager.GetString("urlGooglePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.windowsphone.com/s?appid={0} 的本地化字符串。
        /// </summary>
        internal static string urlMicrosoftStore {
            get {
                return ResourceManager.GetString("urlMicrosoftStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.patreon.com/apkshellext 的本地化字符串。
        /// </summary>
        internal static string urlPatreon {
            get {
                return ResourceManager.GetString("urlPatreon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/kkguo/apkshellext/wiki/Package-information-Pattern-variables 的本地化字符串。
        /// </summary>
        internal static string urlPatternVarWiki {
            get {
                return ResourceManager.GetString("urlPatternVarWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://crowdin.com/project/apkshellext 的本地化字符串。
        /// </summary>
        internal static string urlTranslate {
            get {
                return ResourceManager.GetString("urlTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AppID 的本地化字符串。
        /// </summary>
        internal static string varAppid {
            get {
                return ResourceManager.GetString("varAppid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AppName 的本地化字符串。
        /// </summary>
        internal static string varAppName {
            get {
                return ResourceManager.GetString("varAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attr\((.*),(.*)\) 的本地化字符串。
        /// </summary>
        internal static string varAttribute {
            get {
                return ResourceManager.GetString("varAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debuggable 的本地化字符串。
        /// </summary>
        internal static string varDebuggable {
            get {
                return ResourceManager.GetString("varDebuggable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FileSize 的本地化字符串。
        /// </summary>
        internal static string varFileSize {
            get {
                return ResourceManager.GetString("varFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LastModify 的本地化字符串。
        /// </summary>
        internal static string varLastModify {
            get {
                return ResourceManager.GetString("varLastModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OS 的本地化字符串。
        /// </summary>
        internal static string varOS {
            get {
                return ResourceManager.GetString("varOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package 的本地化字符串。
        /// </summary>
        internal static string varPackage {
            get {
                return ResourceManager.GetString("varPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publisher 的本地化字符串。
        /// </summary>
        internal static string varPublisher {
            get {
                return ResourceManager.GetString("varPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Revision 的本地化字符串。
        /// </summary>
        internal static string varRevision {
            get {
                return ResourceManager.GetString("varRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        internal static string varVersion {
            get {
                return ResourceManager.GetString("varVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap windows {
            get {
                object obj = ResourceManager.GetObject("windows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
